author:
  name: Chelsea Parker
  email: info@thedesignjedi.com
  url: thedesignjedi.com
title: This IS the design site you've been looking for.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/07ee81ba-9032-466b-bb75-dffac5258fbe.png
color:
  saturation: 0.38310391758568585
  brandStrength: 0.19785068440251052
  rhythmicContrast: 0.42630054522305727
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  lightness: 0.32615201571024954
typography_spectrum: 0.627090165624395
layout_spectrum: 0.11661483580246568
name: The Design Jedi
