author:
  name: Chelsea Parker
  email: info@thedesignjedi.com
  url: thedesignjedi.com
title: This IS the design site you've been looking for.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/07ee81ba-9032-466b-bb75-dffac5258fbe.png
color:
  saturation: 0.3961197908502072
  brandStrength: 0.3336048142518848
  rhythmicContrast: 0.2740130184683949
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  lightness: 0.9578185179270804
typography_spectrum: 0.35415531951002777
layout_spectrum: 0.6074987256433815
name: The Design Jedi
