typography_spectrum: 0.9382979
color:
  saturation: 0.3831039175856858
  brandStrength: 0.1978506844025105
  rhythmicContrast: 0.4263005452230573
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  lightness: 0.3261520157102495
layout_spectrum: 0.9
author:
  name: The Design Jedi
  email: info@thedesignjedi.com
  url: thedesignjedi.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/07ee81ba-9032-466b-bb75-dffac5258fbe.png
name: The Design Jedi
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: This IS the design site you've been looking for.
